### ISSUE TITLE
Typo in language models application

### ISSUE THREAD

**Issue by ducnx** [ermongroup/cs228-notes#134]
https://github.com/ermongroup/cs228-notes/blob/dd0ea640f5f6b0c35ca2999d5a06b94fe20e4769/docs/preliminaries/applications/index.html#L167
It should be **language utterances** instead of **langauge utterances**.
The typo also exists in file preliminaries/applications/index.md.

**Comment by chrisyeh96** [comment]
Thanks! This has been fixed in pull request #136.
