### ISSUE TITLE
Generative vs discriminative models

### ISSUE THREAD

**Issue by fkdosilovic** [ermongroup/cs228-notes#161]
I've been reading your notes on PGMs , and also some other resources, particularly [1]. In [1] , in the introduction, they mention the difference between generative and discriminative models, i.e. modelling joint distribution _p(y, **x**)_ opposed to _p(y|**x**)_. You mention the same difference in the _The difficulties of probabilistic modeling_.
The confusing part is in _Real-World Applications/Probabilistic Models of Images_ where you write 
> one of the reasons why generative models are powerful lie in the fact that they have many fewer parameters than the amount of data that they are trained with,

which seems contradictory to the _The difficulties of probabilistic modeling_  section. The confusing part is (in boldface) that the sentence above says that _**generative models have many fewer parameters** than the amount of data that they are trained with_, which is inconsistent with the argument made in _The difficulties of probabilistic modeling_.

Am I interpreting something wrong, or the terminology is ambiguous?

[1] [An Introduction to Conditional Random Fields](https://homepages.inf.ed.ac.uk/csutton/publications/crftutv2.pdf)

**Comment by jiamings** [comment]
I think the idea is that in the deep generative models for images, specific modeling assumptions are made.  In the spam example, one could avoid having $O(2^N)$ parameters by having the Naive Bayes assumption. 

But I think in the deep generative model case, the number of parameters refer more specifically to the parameters in the neural network. For example, in CIFAR10 image modeling, the number of bits are 50k x 3 x 28 x 28 x 8, whereas the state-of-the-art generative models (such as BigGAN for CIFAR10) would only need around 4 million parameters to perform well.
