### ISSUE TITLE
Add a side note that links to a resource that proves that the probability distribution defined on a Bayesian network is valid

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#164]
At the end of the section where you formally describe [Bayesian networks](https://ermongroup.github.io/cs228-notes/representation/directed/), you state

> It is not hard to see that a probability represented by a Bayesian network will be valid: clearly, it will be non-negative and one can show using an induction argument (and using the fact that the CPDs are valid probabilities) that the sum over all variable assignments will be one. Conversely, we can also show by counter-example that when G contains cycles, its associated probability may not sum to one.

I think you should have a side note that links to a paper or a resource that proves these statements.

**Comment by chrisyeh96** [comment]
These statements are not particularly challenging to prove and are left as exercises to the reader. Otherwise, proofs can be found in the course textbook by Daphne and Koller.
