### ISSUE TITLE
Section "Introducing evidence" is unclear

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#166]
The section [Introducing evidence](https://ermongroup.github.io/cs228-notes/inference/ve/) is quite unclear. For example, you say

> P(X, Y, E) is a probability distribution

However, in the equation above that statement there is no term P(X, Y, E).

You say that sometimes we are interested in computing the posterior given the evidence. So, what does X have to do with this?

The following statement

> We can compute this probability by performing variable elimination once on ...

is also not clear. Can you explain it further?

The last paragraph is also quite unclear. What do you mean by scope?

**Comment by chrisyeh96** [comment]
P(Y | E=e) = \sum_x P(X=x, Y | E=e)

where the sum is implied, since VE is all about marginalization.

As described in the section titled "Factor Operations," a scope of a factor is the set of variables that the factor takes as input.

**Comment by nbro** [comment]
@chrisyeh96 Implied? You mean "implicit" or completely absent! I think that should be made explicit.
