### ISSUE TITLE
Confusing notation of the factor-to-variable message in the belief propagation algorithm for trees

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#168]
The following [equation](https://ermongroup.github.io/cs228-notes/inference/jt/) is quite confusing

<img width="526" alt="Screen Shot 2019-05-12 at 19 04 52" src="https://user-images.githubusercontent.com/9349000/57585476-031dd700-74e9-11e9-9c7c-454c23e75966.png">

Specifically, you use x_{\mathcal N(s)} as input to f_s, but the summation is over x_{\mathcal N(s)\setminus i}, whose meaning is not very clear. I think you should clarify this point a little more. Here, $x$ is a random variable, so what could x_{\mathcal N(s)} mean?

**Comment by jiamings** [comment]
I think the \mathcal{N} should be N, which is defined above as all the neighbors of a node.
Will update this later.
