### ISSUE TITLE
Incomprehensible sentence in the section "Junction tree algorithm"

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#169]
In the section [An illustrative example](https://ermongroup.github.io/cs228-notes/inference/jt/), you state

> Crucially, we assume that the cliques c some path structure

Maybe you forgot "form"? So it should be

> Crucially, we assume that the cliques c **form** some path structure

**Comment by chrisyeh96** [comment]
Commit 1d136c0
