### ISSUE TITLE
Sum is not an integral in the section Monte Carlo estimation

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#170]
In the section [Monte Carlo estimation](https://ermongroup.github.io/cs228-notes/inference/sampling/), you say 

> ... as well as computing integrals of the form

But then you show a sum not an integral. Maybe you meant "expectation"?

**Comment by jiamings** [comment]
I believe that the integral implied here is the Lebesgue integral, which could be treated as a weighted sum. See section 2.4 in the notes for more details.
