### ISSUE TITLE
Inconsistency between definition of ELBO in sections "Auto-encoding variational Bayes" and "The variational lower bound"

### ISSUE THREAD

**Issue by nbro** [ermongroup/cs228-notes#171]
In the section [Auto-encoding variational Bayes](https://ermongroup.github.io/cs228-notes/extras/vae/), you state

> Recall that in variational inference, we are interested in maximizing the ...

However, in the section [The variational lower bound](https://ermongroup.github.io/cs228-notes/inference/variational/), you define the expectation in a different way. Specifically, \tilde{p} and q are functions of x (`E[log(p(x)) - log(q(x))]`), whereas in the section [Auto-encoding variational Bayes](https://ermongroup.github.io/cs228-notes/extras/vae/), the distributions are a function of x and z (an unobserved variable) and, further, q is a conditional probability: `E[log(p(x, z)) - log(q(z | x))]`. So, I think you should explain these differences.

**Comment by jiamings** [comment]
Thanks for the comment, in both cases, the task is to perform "inference", in the first case, it is performed over x, in the second case it is performed over z given observations of x. The useful connection between these two is that they use a lower bound to the log partition functions by invoking the Jensen's inequality.
