### ISSUE TITLE
What is g?

### ISSUE THREAD

**Issue by chrisyeh96** [ermongroup/cs228-notes#37]
See this line: https://github.com/ermongroup/cs228-notes/blame/master/inference/sampling/index.md#L35

I'm confused by what g is on this line. Is it supposed to be f? Or was this supposed to be something else entirely?

Same goes for another line: https://github.com/ermongroup/cs228-notes/blame/master/inference/sampling/index.md#L44

**Comment by kuleshov** [comment]
Sorry, it was supposed to be f!
