### ISSUE TITLE
Usage of the term "potentials" in discussion of Markov random fields

### ISSUE THREAD

**Issue by sivark** [ermongroup/cs228-notes#65]
I have a comment regarding the following equation [here](https://github.com/ermongroup/cs228-notes/blob/master/representation/undirected/index.md)
$$\tilde p(A,B,C,D) = \phi(A,B)\phi(B,C)\phi(C,D)\phi(D,A), $$
and the rest of the section where $\phi()$ are referred to as "potentials".

In the language of physics, the potential would refer to the the log likelihood, since potentials *add* when different probability factors *multiply* (just like the energies of different non-interacting subsystems add up). 

It's possible that the jargon got scrambled when moving from one community to another. If the document's usage is consistent with conventions in the field, then it might be worth adding a clarifying footnote where $\phi$ is introduced.

**Comment by ermonste** [comment]
Good point.

**Comment by kuleshov** [comment]
I think "factor" is the right term to use here, and this was a typo. I see that Stefano just did the update.

**Comment by sivark** [comment]
Thanks for the great resource. It's an enjoyable read.
