### ISSUE TITLE
explain the chain rule?

### ISSUE THREAD

**Issue by cswarth** [ermongroup/cs228-notes#69]
In [Bayesian Networks](https://ermongroup.github.io/cs228-notes/representation/directed/) (the first meaty chapter), 

> Recall that by the chain rule, we can write any probability pp as...

Search Probability review for definition of the chain rule - nothing.  
Search any earlier chapter for mention of the chain rule - nothing.

**Comment by ermonste** [comment]
good catch! thanks!
