### ISSUE TITLE
preliminaries/introduction "Thus, it will best" should be "Thus, it will be best"

### ISSUE THREAD

**Issue by bayofislands** [ermongroup/cs228-notes#78]
A bird’s eye overview of the course

Our discussion of graphical models will be divided into three major parts: representation (how to specify a model), inference (how to ask the model questions), and learning (how to fit a model to real-world data). These three themes will also be closely linked: to derive efficient inference and learning algorithms, the model will need to be adequately represented; furthermore, learning models will require inference as a subroutine. **Thus, it will best** to always keep the three tasks in mind, rather than focusing on them in isolation . . .

**Comment by ermonste** [comment]
thanks, fixed
